### ISSUE TITLE
Throws exception when trying to run   Geocoder.local.findAddressesFromCoordinates(coordinates) only on Android 

### ISSUE THREAD

**Issue by spiderion** [aloisdeniel/flutter_geocoder#25] opened 2019-07-13 15:14 UTC
E/AndroidRuntime(20142): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(20142): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime(20142): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(20142): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(20142): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(20142): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(20142): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(20142): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20142): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(20142): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
E/AndroidRuntime(20142): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(20142): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime(20142): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime(20142): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(20142): 	at com.aloisdeniel.geocoder.GeocoderPlugin$2.doInBackground(GeocoderPlugin.java:109)
E/AndroidRuntime(20142): 	at com.aloisdeniel.geocoder.GeocoderPlugin$2.doInBackground(GeocoderPlugin.java:102)
E/AndroidRuntime(20142): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(20142): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(20142): 	... 4 more
D/EGL_emulation(20142): eglMakeCurrent: 0xe8be2640: ver 3 0 (tinfo 0xe4c682b0)
E/BufferQueueProducer(20142): [SurfaceTexture-0-20142-0] setAsyncMode: BufferQueue has been abandoned
E/BufferQueueProducer(20142): [SurfaceTexture-0-20142-0] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20142): [SurfaceTexture-0-20142-0] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20142): [SurfaceTexture-0-20142-0] setAsyncMode: BufferQueue has been abandoned
W/System  (20142): A resource failed to call release.

**Comment by Emelio** [comment] 2019-07-15 12:10
Any fix yet, I am having the same issue.

**Comment by julianmarangoni** [comment] 2019-07-15 14:23
This has been broken for awhile for me. Looks like its a threading issue on android:

> Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask

Issue looks like its caused by:

> result.success(createAddressMapList(addresses));

GeocoderPlugin.java line 79.

The "success" function is marked with @UiThread, and its being executed inside an AsyncTask.

**Comment by Emelio** [comment] 2019-07-15 18:06
Do you have any idea of what can be done as a workaround until someone is able to fix this?

**Comment by julianmarangoni** [comment] 2019-07-15 18:12
> Do you have any idea of what can be done as a workaround until someone is able to fix this?

Fixed it by following solution in https://github.com/aloisdeniel/flutter_geocoder/issues/24#issuecomment-511361511

**Comment by aloisdeniel** [comment] 2019-07-17 05:17
It should be fixed [0.2.1 version](https://pub.dev/packages/geocoder/versions/0.2.1).

Thanks for reporting!

**Closed as completed by aloisdeniel** 2019-07-17 05:17 UTC
